const title = document.querySelector("#title")
const subTitle = document.querySelector("#subTitle")
const btnLightMode = document.querySelector("#lightMode")
const btnDarkMode = document.querySelector("#darkMode")
const html = document.querySelector("#html")

btnLightMode.addEventListener('click', () => html.style.backgroundColor = "white")
btnLightMode.addEventListener('click', () => title.style.color = "black")
btnLightMode.addEventListener('click', () => title.style.backgroundColor = "white")
btnLightMode.addEventListener('click', () => subTitle.style.color = "black")
btnLightMode.addEventListener('click', () => subTitle.style.backgroundColor = "white")
btnLightMode.addEventListener('click', () => btnLightMode.style.color = "black")
btnLightMode.addEventListener('click', () => btnLightMode.style.backgroundColor = "white")
btnLightMode.addEventListener('click', () => btnDarkMode.style.color = "black")
btnLightMode.addEventListener('click', () => btnDarkMode.style.backgroundColor = "white")

btnDarkMode.addEventListener('click', () => html.style.backgroundColor = "black")
btnDarkMode.addEventListener('click', () => title.style.color = "white")
btnDarkMode.addEventListener('click', () => title.style.backgroundColor = "black")
btnDarkMode.addEventListener('click', () => subTitle.style.color = "white")
btnDarkMode.addEventListener('click', () => subTitle.style.backgroundColor = "black")
btnDarkMode.addEventListener('click', () => btnLightMode.style.color = "white")
btnDarkMode.addEventListener('click', () => btnLightMode.style.backgroundColor = "black")
btnDarkMode.addEventListener('click', () => btnDarkMode.style.color = "white")
btnDarkMode.addEventListener('click', () => btnDarkMode.style.backgroundColor = "black")